### ISSUE TITLE
Failing on CentOS 7 Vanilla

### ISSUE THREAD

**Issue by sajinvasudevan** [donapieppo/libnss-ato#10]
Tried the below test after installing from source on CentOS 7 Vanilla

```
If you add libnss-ato to the chain of nss modules (in /etc/nsswitch.conf) you get something like:
]$ id randomname ]$ uid=1000(user_test) gid=1000 groups=1000
for every query of a random username not present in /etc/passwd.
```
Got the below output
```
# id randomuser
id: randomuser:  no such user
#
```
Is there anything else to be done on CentOS 7 specially, I got this working on Centos 6 without any issues.
Please let me know for any additional information.

Thanks.

**Comment by donapieppo** [comment]
Have you tried to compile and install directly from source?
Unfortunately I don't have experience with rpm (I am an apt user) or centos.

**Comment by sajinvasudevan** [comment]
Yes, I've complied directly from source (make/make install), which I followed for CentOS 6

**Comment by donapieppo** [comment]
Please try to create a link in /lib64 to the libnss_ato-2.3.6.so like this

`ln -sf /lib/libnss_ato-2.3.6.so /lib64/libnss_ato.so.2`

and let me know if it works.

**Comment by sajinvasudevan** [comment]
Wow! that made it to work. Thank a lot.
