### ISSUE TITLE
passwd: Authentication token manipulation error

### ISSUE THREAD

**Issue by Jnchi** [donapieppo/libnss-ato#16]
```terminal
cat /etc/libnss-ato.conf
ubuntu:x:1000:1000::/home/ubuntu:/bin/bash
getent passwd jnchi
jnchi:x:1000:1000::/home/ubuntu:/bin/bash
passwd jnchi
passwd: Authentication token manipulation error
passwd: password unchanged
```

I am working on a PAM module to authenticate against Azure Active Directory (See: [CyberNinjas/pam_aad](https://github.com/CyberNinjas/pam_aad)).

See also: https://github.com/CyberNinjas/pam_aad/issues/21#issuecomment-448733152

**Comment by Jnchi** [comment]
So would the PAM module insert the password into `/etc/shadow`?

**Comment by donapieppo** [comment]
It depends on the pam module you use for authentication. From your message it seems you use Active Directory. The password so are in the AD server. Libnss-ato has no knowlege of where your service checks the passwords. Libnss-ato is just to give uid and gid to the users not present in /etc/passwod. For this reason libnss-ato has no role in changing the password.

**Comment by Jnchi** [comment]
> From your message it seems you use Active Directory. The password so are in the AD server.

This module is for _Azure Active Directory_. Apparently, it is very different from regular Active Directory.

Anyway, thanks for the input! If I have more questions pertaining to uid or gid then I'll open another issue. Cheers!
