### ISSUE TITLE
libnss-ato considers test_user:test_group as username

### ISSUE THREAD

**Issue by cs10249mitt** [donapieppo/libnss-ato#18]
Is it possible to limit libnss ato functionality to skip names like "test_name.test_group". This creates an issue that command like "chown test_user.test_group a" to treat "test_user.test_group" as a username where chown would want "test_user" as username and "test_group" as the usergroup.
Same is the issue with "test_user:test_group"

**Comment by donapieppo** [comment]
I suggest that you create a file like /etc/nsswitch.conf.ato (with passwd: files ato)
and /etc/nsswitch.conf.noato (with passwd: files)

Then to chown (or orther commands of the kind):

```bash
cp /etc/nsswitch.conf.noato /etc/nsswitch.conf
chown test_user.test_group a
cp /etc/nsswitch.conf.ato /etc/nsswitch.conf
```
For example with active directory users have usually name.surname kind of usernames so I don't think if would be wise to skip these.

**Comment by cs10249mitt** [comment]
For active directory users isnt it suggested to use libnss-ldap, which i believe will check with ldap/ad to findout if the user is a valid user on server.
To my understanding libnss-ato has more of a usecase for RADIUS where RADIUS server doesnt allow to verify a username without authenticating him first.

Also looks like libnss-ato matches even digits/numbers as valid Usernames. I feel we should have some sort of validation. Please advise

**Comment by donapieppo** [comment]
The problem with libnss-ldap and AD in big domains is listing all users (for example ls -l in a big directory). I use to replicate part of AD users on caching ldap server for some services or use libnss-ato in simpler case (when for example I don't need different unix ids for different users, that was the original need for writing the library).

But I agree with you that a user defined filter for valid usernames would be useful. Any idea for configuration syntax?

**Comment by cs10249mitt** [comment]
IMHO, A good start would be to not allow Numbers and ":" in the username. 
Ideal would be to make the accept the valid username format as an configuration parameter in the "*.conf" file. 
Please let me know what you think

**Comment by donapieppo** [comment]
Have added #define BAD_CHARS ":" in libnss_ato.c.
You can add all the forbidden characters in this new variable.

If you change BAD_CHARS ":.12345" and recompile you get:

```bash
id pippo
uid=1000(testuser) gid=1000(testuser) groups=1000(testuser)

id pippo1
id: 'pippo1': no such user

id pippo9
uid=1000(testuser) gid=1000(testuser) groups=1000(testuser)

id pippo:pluto
id: 'pippo:pluto': no such user
```

Hope it helps.

Ciao

Pietro

**Comment by cs10249mitt** [comment]
Sounds good to me 
Thanks so much
