### ISSUE TITLE
How to get working sudo su for user ?

### ISSUE THREAD

**Issue by jozefrebjak** [donapieppo/libnss-ato#20]
I am using this library with pam_tacacs. I can log in with tacacs user as a configured user in conf. But I can't switch to `root`. How to specify more groups ? 

because when I run id test_user

I am getting 

```id=1000(test_user) gid=1000(test_user) groups=1000(test_user),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),111(lpadmin),112(sambashare)```

and when I am logged in with tacacs user test_user and I run `id` I'm getting only

```
uid=1000(test_user) gid=1000(test_user) groups=1000(test_user)
```

in `passwd` it's like:

```
test_user:x:1000:1000:Test User,,,:/home/jrebjak:/bin/bash
```

and in `libnss-ato.conf` I have

```
test_user:x:1000:1000,27:Test User,,,:/home/jrebjak:/bin/bash
```

**Comment by donapieppo** [comment]
You are right. 
I think this is because libnss_ato does not implement the _nss_ato_getgrnam_r.
I will take a look.
Maybe for the sudo problem you can have a temporary solution configuring /etc/sudoers
