### ISSUE TITLE
Is there any opensource alternative of libnss-ato?

### ISSUE THREAD

**Issue by sshedi** [donapieppo/libnss-ato#21]
Hi All,

It looks like this project is not maintained anymore (Last commit was 4 years ago).

I'm looking for an equivalent or better alternative for libnss-ato which is actively maintained. Any suggestions?
Thanks.

**Comment by donapieppo** [comment]
Hi, 
I think all the [forks](https://github.com/donapieppo/libnss-ato/forks) are also inactive and I am not aware of alterantives.
The code is quite simple and small, are there any particular improvements you are missing?

**Comment by sshedi** [comment]
Hi @donapieppo ,

Thanks for the response. I'm not looking for any fixes or feature additions. Just want to know if the project is actively maintained. There are no new commits from a long time now. So, need clarity on whether we can keep this package in our repo or not.

**Comment by sshedi** [comment]
Thanks for your prompt responses @donapieppo. Have a nice time ahead.
